#!/bin/bash
#
# A wrapper around around commands to convert stdin to signals.
#
# Usage:
#     ./sig-wrapper ARGS
#
#     ./sig-wrapper java -Dsolr.solr.home=. -Djetty.port=7981 -jar start.jar"

# enable job control in order to trap CHLD signals
set -m

CHILD=""

handle_msg()
{
    msg=$1

    case $msg in
        INT)
            echo "INT msg received, sending INT signal to PID $CHILD"
            kill_and_exit
            ;;
        *)
            echo "Unknown msg received $msg"
    esac
}

kill_and_exit()
{
    if [ "$CHILD" == "" ]
    then
        echo "No PID to stop"
        exit 1
    else
        echo "Stopping PID $CHILD"
        kill -TERM $CHILD
        exit 0
    fi
}

pid_died()
{
    echo "The PID $CHILD died"
    exit 1
}

trap kill_and_exit INT TERM QUIT
trap pid_died CHLD

trap -p

"$@" &
CHILD=$!

while true
do
    if read -t 1 msg
    then
        handle_msg $msg
    fi
done
